# Java to PATH. It's is necessary by cmake to build OpenCV Java binding
RUN PATH=$PATH:$JAVA_HOME

# Dependencies for building
RUN yum install -y epel-release && \
    yum install -y git gcc gcc-c++ make cmake3 qt5-qtbase-devel cmake ant \
        gtk2-devel libpng-devel jasper-devel openexr-devel libwebp-devel \
        libjpeg-turbo-devel libtiff-devel  libdc1394-devel tbb-devel eigen3-devel gstreamer-plugins-base-devel \
        freeglut-devel mesa-libGL mesa-libGL-devel boost boost-thread boost-devel libv4l-devel && \
    # Clone
    git clone https://github.com/opencv/opencv.git /tmp/opencv && \
    cd /tmp/opencv && \
    git checkout 744798aadd1a268a474d38cd27f2e0844b79fd7b && \
    # Build and install
    mkdir build && cd build && \
    cmake3 -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr \
        -D BUILD_TESTS=OFF \
        -D BUILD_EXAMPLES=OFF \
        -D BULD_JAVA=ON \
        -D BUILD_opencv_java=ON \
        -D BUILD_opencv_python3=OFF \
        -D BUILD_opencv_python_bindings_generator=OFF \
        -D BUILD_opencv_python_tests=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D INSTALL_TESTS=OFF .. && \
    make -j $(nproc --all) && \
    make install && \
    # Rebuild the libraries cache
    ln -s /usr/local/lib64/pkgconfig/opencv4.pc /usr/share/pkgconfig/ && ldconfig && \
    # Make library visable to Java
    ln -s /usr/share/java/opencv4/libopencv_java412.so /usr/lib64/libopencv_java412.so && \
    # Clean repo files
    rm -Rf /tmp/opencv